# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77dbc1e9b7ee8d62882993bf256f4954c7301613d9ceb9f05cafdd862dd4e80729dcab1741c583e916fc62d58676f96b25c1590c5f29da353e9a8e4483e94cf8

test:
  secret_key_base: 3bbd6ad1a5a1deb26a857c2f4740cb4765e4c03b183f540985b6c4c33889daaf92248d4f4b45be7b600468b8c21f5693db2e39325afc819a47be2c167c8cd4b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
